const rows = [
  {
    id: 1,
    name: "Snow",
    email: "show@gmail.com",
    age: 14,
    phone: 1000000,
    access: "Manager",
  },
  {
    id: 2,
    name: "Lannister",
    email: "Lannister@gmail.com",
    age: 31,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 3,
    name: "Lannister",
    email: "Lannister@gmail.com",
    age: 31,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 4,
    name: "Stark",
    email: "Stark@gmail.com",
    age: 11,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 5,
    name: "Targaryen",
    email: "Targaryen@gmail.com",
    age: 54,
    phone: 1000000,
    access: "User",
  },
  {
    id: 6,
    name: "Melisandre",
    email: "Melisandre@gmail.com",
    age: 150,
    phone: 1000000,
    access: "User",
  },
  {
    id: 7,
    name: "Clifford",
    email: "Clifford@gmail.com",
    age: 44,
    phone: 1000000,
    access: "User",
  },
  {
    id: 8,
    name: "Frances",
    email: "Frances@gmail.com",
    age: 36,
    phone: 1000000,
    access: "User",
  },
  {
    id: 9,
    name: "Roxie",
    email: "Roxie@gmail.com",
    age: 65,
    phone: 1000000,
    access: "User",
  },
  {
    id: 10,
    name: "Snow",
    email: "show@gmail.com",
    age: 14,
    phone: 1000000,
    access: "Manager",
  },
  {
    id: 11,
    name: "Lannister",
    email: "Lannister@gmail.com",
    age: 31,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 12,
    name: "Lannister",
    email: "Lannister@gmail.com",
    age: 31,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 13,
    name: "Stark",
    email: "Stark@gmail.com",
    age: 11,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 14,
    name: "Targaryen",
    email: "Targaryen@gmail.com",
    age: 54,
    phone: 1000000,
    access: "User",
  },
  {
    id: 15,
    name: "Melisandre",
    email: "Melisandre@gmail.com",
    age: 150,
    phone: 1000000,
    access: "User",
  },
  {
    id: 16,
    name: "Clifford",
    email: "Clifford@gmail.com",
    age: 44,
    phone: 1000000,
    access: "User",
  },
  {
    id: 17,
    name: "Frances",
    email: "Frances@gmail.com",
    age: 36,
    phone: 1000000,
    access: "User",
  },
  {
    id: 18,
    name: "Roxie",
    email: "Roxie@gmail.com",
    age: 65,
    phone: 1000000,
    access: "User",
  },
  {
    id: 19,
    name: "Snow",
    email: "show@gmail.com",
    age: 14,
    phone: 1000000,
    access: "Manager",
  },
  {
    id: 20,
    name: "Lannister",
    email: "Lannister@gmail.com",
    age: 31,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 21,
    name: "Lannister",
    email: "Lannister@gmail.com",
    age: 31,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 22,
    name: "Stark",
    email: "Stark@gmail.com",
    age: 11,
    phone: 1000000,
    access: "Admin",
  },
  {
    id: 23,
    name: "Targaryen",
    email: "Targaryen@gmail.com",
    age: 54,
    phone: 1000000,
    access: "User",
  },
  {
    id: 24,
    name: "Melisandre",
    email: "Melisandre@gmail.com",
    age: 150,
    phone: 1000000,
    access: "User",
  },
  {
    id: 25,
    name: "Clifford",
    email: "Clifford@gmail.com",
    age: 44,
    phone: 1000000,
    access: "User",
  },
  {
    id: 26,
    name: "Frances",
    email: "Frances@gmail.com",
    age: 36,
    phone: 1000000,
    access: "User",
  },
  {
    id: 27,
    name: "Roxie",
    email: "Roxie@gmail.com",
    age: 65,
    phone: 1000000,
    access: "User",
  },
];

export default rows;
